"""A curated subset of MITRE ATT&CK (Enterprise) techniques relevant to the
platform's findings and detections. Reference data only."""
from __future__ import annotations

MITRE_TECHNIQUES: list[dict] = [
    {"technique_id": "T1595", "name": "Active Scanning", "tactic": "Reconnaissance",
     "description": "Adversaries probe victim infrastructure via scanning.",
     "url": "https://attack.mitre.org/techniques/T1595/"},
    {"technique_id": "T1592", "name": "Gather Victim Host Information", "tactic": "Reconnaissance",
     "description": "Collecting information about victim hosts, e.g. software versions.",
     "url": "https://attack.mitre.org/techniques/T1592/"},
    {"technique_id": "T1190", "name": "Exploit Public-Facing Application",
     "tactic": "Initial Access",
     "description": "Exploiting a weakness in an Internet-facing application (e.g. SQL injection).",
     "url": "https://attack.mitre.org/techniques/T1190/"},
    {"technique_id": "T1189", "name": "Drive-by Compromise", "tactic": "Initial Access",
     "description": "Gaining access through a user visiting a compromised or malicious page.",
     "url": "https://attack.mitre.org/techniques/T1189/"},
    {"technique_id": "T1110", "name": "Brute Force", "tactic": "Credential Access",
     "description": "Systematically guessing credentials.",
     "url": "https://attack.mitre.org/techniques/T1110/"},
    {"technique_id": "T1078", "name": "Valid Accounts", "tactic": "Defense Evasion",
     "description": "Using legitimate credentials to gain or maintain access.",
     "url": "https://attack.mitre.org/techniques/T1078/"},
    {"technique_id": "T1046", "name": "Network Service Discovery", "tactic": "Discovery",
     "description": "Enumerating services running on remote hosts (port scanning).",
     "url": "https://attack.mitre.org/techniques/T1046/"},
    {"technique_id": "T1071", "name": "Application Layer Protocol",
     "tactic": "Command and Control",
     "description": "Communicating over common application-layer protocols.",
     "url": "https://attack.mitre.org/techniques/T1071/"},
    {"technique_id": "T1499", "name": "Endpoint Denial of Service", "tactic": "Impact",
     "description": "Degrading availability of a targeted service.",
     "url": "https://attack.mitre.org/techniques/T1499/"},
    {"technique_id": "T1213", "name": "Data from Information Repositories",
     "tactic": "Collection",
     "description": "Accessing repositories that may expose sensitive information.",
     "url": "https://attack.mitre.org/techniques/T1213/"},
]
